#!/bin/bash
set -e

aws sts get-caller-identity &>/dev/null || aws sso login

tmuxinator start adrs
tmuxinator start zp
tmuxinator start sea-turtle
tmuxinator start web
tmuxinator start em
tmuxinator start pro
tmuxinator start gusto-lift
tmuxinator start gusto-eventing
tmuxinator start gusto-rebac
tmuxinator start rebac
tmuxinator start pianobar
tmux attach
