#!/bin/bash

nowplaying="/tmp/pianobar_nowplaying"
quit_sentinel="$HOME/.config/pianobar/quit-sentinel"

case "$1" in
    songstart)
        while read L; do
            k="${L%%=*}"
            v="${L#*=}"
            export "$k"="$v"
        done
        echo "▶ $artist - $title" > "$nowplaying"
        ;;
    songpause)
        sed -i '' 's/^▶/⏸/' "$nowplaying"
        ;;
    songresume)
        sed -i '' 's/^⏸/▶/' "$nowplaying"
        ;;
    userquit)
        rm -f "$nowplaying"
        touch "$quit_sentinel"
        ;;
esac
